### ISSUE TITLE
Next.js 11 Support

### ISSUE THREAD

**Issue by blaizze** [ryanhefner/next-contentful#8]
Since Next.js guys have removed [Head.rewind()](https://nextjs.org/docs/upgrading#remove-headrewind) from version 11, now code throws an error:

```
TypeError: _head.default.rewind is not a function
    at _callee$ (/Projects/project-name/node_modules/next-contentful/withContentful.js:129:36)
    at tryCatch (/Projects/project-name/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Projects/project-name/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.throw (/Projects/project-name/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Projects/project-name/node_modules/next-contentful/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/Projects/project-name/next-contentful/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
```

**Comment by Fanda36** [comment]
You can safely remove this line (you can use https://www.npmjs.com/package/patch-package):

```diff
diff --git a/node_modules/next-contentful/src/withContentful.js b/node_modules/next-contentful/src/withContentful.js
index 347000a..72f8bc9 100644
--- a/node_modules/next-contentful/src/withContentful.js
+++ b/node_modules/next-contentful/src/withContentful.js
@@ -68,7 +68,8 @@ export default function withContentful({ accessToken, host, space, environment,
 
           // getDataFromTree does not call componentWillUnmount
           // head side effect therefore need to be cleared manually
-          Head.rewind();
+          // it should be save to remove https://nextjs.org/docs/upgrading#remove-headrewind
+          // Head.rewind();
         }
 
         // Pass in the Contentful client credentials and initial cache state
diff --git a/node_modules/next-contentful/withContentful.js b/node_modules/next-contentful/withContentful.js
index ad6ae9e..a64c710 100644
--- a/node_modules/next-contentful/withContentful.js
+++ b/node_modules/next-contentful/withContentful.js
@@ -126,7 +126,8 @@ function withContentful(_ref) {
                 case 16:
                   // getDataFromTree does not call componentWillUnmount
                   // head side effect therefore need to be cleared manually
-                  _head["default"].rewind();
+                  // it should be save to remove https://nextjs.org/docs/upgrading#remove-headrewind
+                  // _head["default"].rewind();
 
                 case 17:
                   // Pass in the Contentful client credentials and initial cache state
```
